name: Create Repo in GitHub organization

on:
  workflow_dispatch:

jobs:
  create-repo-in-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create repo in organization
        uses: ./provisioner/actions/create-repo
        with:
          ORG_NAME: suryakaiser
          REPO_NAME: test-repo
          HOSTNAME: ${{ secrets.HOST_NAME }}
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
          DESCRIPTION: First repo
